/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Precinto;

import Controlador.LibreriaBDControlador;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ángel González Rincón
 * Fecha: 17-Ago-2021
 */
public class catalogoPrecinto extends javax.swing.JFrame {

    String columna[];
    DefaultTableModel modeloPrecinto;
    LibreriaBDControlador lbd = new LibreriaBDControlador();    
    public catalogoPrecinto() {
        lbd.openConnection();
        getColumnas();
        modeloPrecinto = lbd.modeloPrecinto(columna); //Cargo el contenido por defecto
        lbd.closeConnection();        
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Multimedia/icono_GasValid.jpg")).getImage());
        
    }

    String[] getColumnas(){
            columna = new String[] {"ID_Precinto","nPrecinto",
            "Holograma",
            "Tipo",
            };
        return columna;
    }    
    
    private void RefrescarCTctionPerformed(java.awt.event.ActionEvent evt) {                                            
        lbd.openConnection();
        modeloPrecinto = lbd.modeloPrecinto(columna);
        lbd.closeConnection();
        tablaPrecinto.setModel(modeloPrecinto);
        modeloPrecinto.fireTableDataChanged();
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonAgregarPrecinto = new javax.swing.JButton();
        botonEditarPrecinto = new javax.swing.JButton();
        botonEliminarPrecinto = new javax.swing.JButton();
        botonBuscarNPrecinto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nPrecintoTextField = new javax.swing.JTextField();
        RefrescarTablaPrecinto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPrecinto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Catálogo Precinto");
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        botonAgregarPrecinto.setText("Agregar");
        botonAgregarPrecinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPrecintoActionPerformed(evt);
            }
        });

        botonEditarPrecinto.setText("Editar");
        botonEditarPrecinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarPrecintoActionPerformed(evt);
            }
        });

        botonEliminarPrecinto.setText("Eliminar");
        botonEliminarPrecinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPrecintoActionPerformed(evt);
            }
        });

        botonBuscarNPrecinto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonBuscarNPrecinto.setText("Buscar");
        botonBuscarNPrecinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarNPrecintoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Número de Precinto:");

        RefrescarTablaPrecinto.setText("Refrescar");
        RefrescarTablaPrecinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefrescarTablaPrecintoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAgregarPrecinto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEditarPrecinto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEliminarPrecinto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nPrecintoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonBuscarNPrecinto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RefrescarTablaPrecinto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregarPrecinto)
                    .addComponent(jLabel1)
                    .addComponent(nPrecintoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEditarPrecinto)
                    .addComponent(botonBuscarNPrecinto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminarPrecinto)
                    .addComponent(RefrescarTablaPrecinto))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tablaPrecinto.setModel(modeloPrecinto);
        jScrollPane1.setViewportView(tablaPrecinto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarPrecintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPrecintoActionPerformed
        eliminarPrecinto elp = new eliminarPrecinto(this, true);
        elp.show();
        RefrescarCTctionPerformed(evt);        
    }//GEN-LAST:event_botonEliminarPrecintoActionPerformed

    private void botonAgregarPrecintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPrecintoActionPerformed
        agregarPrecinto ap = new agregarPrecinto(this, true);
        ap.show();
        RefrescarCTctionPerformed(evt);
    }//GEN-LAST:event_botonAgregarPrecintoActionPerformed

    private void botonEditarPrecintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarPrecintoActionPerformed
        editarPrecinto ep = new editarPrecinto(this, true);
        ep.show();
        RefrescarCTctionPerformed(evt);
    }//GEN-LAST:event_botonEditarPrecintoActionPerformed

    private void botonBuscarNPrecintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarNPrecintoActionPerformed
        String n_precinto = nPrecintoTextField.getText();
        lbd.openConnection();
        modeloPrecinto = lbd.modeloPrecintoBuscar(columna, n_precinto);
        lbd.closeConnection();
        tablaPrecinto.setModel(modeloPrecinto);
        modeloPrecinto.fireTableDataChanged();
    }//GEN-LAST:event_botonBuscarNPrecintoActionPerformed

    private void RefrescarTablaPrecintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefrescarTablaPrecintoActionPerformed
        lbd.openConnection();
        modeloPrecinto = lbd.modeloPrecinto(columna);
        lbd.closeConnection();
        tablaPrecinto.setModel(modeloPrecinto);
        modeloPrecinto.fireTableDataChanged();
        nPrecintoTextField.setText("");
    }//GEN-LAST:event_RefrescarTablaPrecintoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(catalogoPrecinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(catalogoPrecinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(catalogoPrecinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(catalogoPrecinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new catalogoPrecinto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RefrescarTablaPrecinto;
    private javax.swing.JButton botonAgregarPrecinto;
    private javax.swing.JButton botonBuscarNPrecinto;
    private javax.swing.JButton botonEditarPrecinto;
    private javax.swing.JButton botonEliminarPrecinto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nPrecintoTextField;
    private javax.swing.JTable tablaPrecinto;
    // End of variables declaration//GEN-END:variables
}
