/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Termometro;
import Controlador.LibreriaBDControlador;
import Modelo.modeloTablaUsuario;
import Vista.Hologramas.modificarHolograma;
import Vista.Termometro.agregarTermometro;
import Vista.Termometro.editarTermometro;
import Vista.Termometro.eliminarTermometro;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Saul Arenas Ramirez
 */
public class catalogoTermometro extends javax.swing.JDialog {
  public String columna[];
    LibreriaBDControlador lbd = new LibreriaBDControlador();
    DefaultTableModel modeloTermometros;
    modeloTablaUsuario mtu = new modeloTablaUsuario();
    int tipoUsuario = 0;

    public catalogoTermometro(modeloTablaUsuario mtu) {
        this.mtu = mtu;
        tipoUsuario = mtu.getTipoUsuario();
        getColumnas();
        lbd.openConnection();
        modeloTermometros = lbd.modeloTermometros(columna); //Cargo el contenido por defecto
        lbd.closeConnection();

        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Multimedia/icono_GasValid.jpg")).getImage());
        //Valido eltipo de usuario
        if(tipoUsuario != 0){
            editarCT.setEnabled(false);
            eliminarCT.setEnabled(false);
        }
        tablaCatalogoTermometros.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = tablaCatalogoTermometros.rowAtPoint(evt.getPoint());
                int col = 0;
                if (row >= 0 && col >= 0) {
                    String valor = tablaCatalogoTermometros.getModel().getValueAt(row, col).toString(); //Tomo el valor de el modelo de la tabla
                }

            }
        });

    }//fincatalogoTermometro
    
    String[] getColumnas(){ //Columnas
            columna = new String[] {"id_Termo",
            "marca",
            "modelo",
            "serie",
            "estatus",
            "fecha_calibracion",
            "resultado",
            "informe_calibracion"};
        return columna;
    }
    
        private void RefrescarCTctionPerformed(java.awt.event.ActionEvent evt) {                                            
        lbd.openConnection();
        modeloTermometros = lbd.modeloTermometros(columna);
        lbd.closeConnection();
        tablaCatalogoTermometros.setModel(modeloTermometros);
        modeloTermometros.fireTableDataChanged();
    }   
    
    

    /**
     * Creates new form catalogoTermometro
     */
    public catalogoTermometro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCatalogoTermometros = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        agregarCT = new javax.swing.JButton();
        editarCT = new javax.swing.JButton();
        eliminarCT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));

        tablaCatalogoTermometros.setModel(modeloTermometros);
        jScrollPane1.setViewportView(tablaCatalogoTermometros);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(204, 204, 255));

        agregarCT.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        agregarCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/edit_add.png"))); // NOI18N
        agregarCT.setText("Agregar");
        agregarCT.setPreferredSize(new java.awt.Dimension(120, 33));
        agregarCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCTActionPerformed(evt);
            }
        });

        editarCT.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        editarCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/modify.png"))); // NOI18N
        editarCT.setText("Editar");
        editarCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCTActionPerformed(evt);
            }
        });

        eliminarCT.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        eliminarCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/trash_can3_delete.png"))); // NOI18N
        eliminarCT.setText("Eliminar");
        eliminarCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(agregarCT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editarCT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(eliminarCT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editarCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarCT, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(agregarCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setForeground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Bienvenido al Catalogo de Termometros, aquí pueden visualizarse los termometros disponibles en el sistema.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCTActionPerformed
agregarTermometro abrir=new agregarTermometro(new javax.swing.JFrame(), true);
        abrir.show();
        RefrescarCTctionPerformed(evt);
    }//GEN-LAST:event_agregarCTActionPerformed

    private void editarCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCTActionPerformed
        editarTermometro abrir=new editarTermometro(new javax.swing.JFrame(), true);
        abrir.show();
        RefrescarCTctionPerformed(evt);
    }//GEN-LAST:event_editarCTActionPerformed

    private void eliminarCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCTActionPerformed
        eliminarTermometro abrir=new eliminarTermometro(new javax.swing.JFrame(), true);
        abrir.show();
        RefrescarCTctionPerformed(evt);
    }//GEN-LAST:event_eliminarCTActionPerformed

    /*
     * @param args the command line arguments
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarCT;
    private javax.swing.JButton editarCT;
    private javax.swing.JButton eliminarCT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCatalogoTermometros;
    // End of variables declaration//GEN-END:variables
}
