/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Hologramas;

import Controlador.LibreriaBDControlador;
import Modelo.modeloTablaUsuario;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yuliana adame
 */
public class catalogoHologramas extends javax.swing.JFrame {

    /**
     * Creates new form catalogoHologramas
     */
    public String columna[];
    LibreriaBDControlador lbd = new LibreriaBDControlador();
    DefaultTableModel modeloHologramas;
    modeloTablaUsuario mtu = new modeloTablaUsuario();
    int tipoUsuario = 0;
    public catalogoHologramas(modeloTablaUsuario mtu) {
        this.mtu = mtu;
        tipoUsuario = mtu.getTipoUsuario();
        getColumnas();
        lbd.openConnection();
        modeloHologramas = lbd.modeloGasValid(columna,"","",""); //Cargo el contenido por defecto
        lbd.closeConnection();
        //setFilas(); //Añado las filas
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Multimedia/icono_GasValid.jpg")).getImage());
        //Valido eltipo de usuario
        if(tipoUsuario != 0){
            ModificarEstatusCH.setEnabled(false);
            eliminarFolio.setEnabled(false);
        }
        
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = jTable1.rowAtPoint(evt.getPoint());
                int col = 0;
                if (row >= 0 && col >= 0) {
                    String valor = jTable1.getModel().getValueAt(row, col).toString(); //Tomo el valor de el modelo de la tabla
                    folioHolograma.setText(valor); //Obtengo el valor del textfield
                }
//                col = 1;
//                if (row >= 0 && col >= 0) {
//                    String valor = jTable1.getModel().getValueAt(row, col).toString(); //Tomo el valor de el modelo de la tabla
//                    jTextField2.setText(valor); //Obtengo el valor del textfield
//                }
//                col = 2;
//                if (row >= 0 && col >= 0) {
//                    String valor = jTable1.getModel().getValueAt(row, col).toString(); //Tomo el valor de el modelo de la tabla
//                    jTextField4.setText(valor); //Obtengo el valor del textfield
//                }
            }
        });
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTable1.setDefaultRenderer(String.class, centerRenderer);
    }
    /*Obtengo los titulos de mi tabla*/
    String[] getColumnas(){ //Columnas
            columna = new String[] {"HOLOGRAMA",
            "NÚM. SOLICITUD",
            "F.VERIFICAR",
            "NÚM. ESTACION",
            "ESTACIÓN",
            "DISPENSARIO",
            "MODELO",
            "MAGUERA",
            "LADO",
            "STATUS"};
        return columna;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        ModificarEstatusCH = new javax.swing.JButton();
        eliminarFolio = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        MostrarTodasCH = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        folioHolograma = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tipoCalcomania = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        estatusHolograma = new javax.swing.JComboBox();
        RefrescarCH = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        AgregarCH1 = new javax.swing.JButton();
        GenerarCH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Catálogo Hologramas");
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jTable1.setModel(modeloHologramas);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        ModificarEstatusCH.setText("Modificar ");
        ModificarEstatusCH.setFocusable(false);
        ModificarEstatusCH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ModificarEstatusCH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ModificarEstatusCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarEstatusCHActionPerformed(evt);
            }
        });

        eliminarFolio.setText("Eliminar Folio");
        eliminarFolio.setFocusable(false);
        eliminarFolio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminarFolio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminarFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarFolioActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        MostrarTodasCH.setForeground(new java.awt.Color(255, 0, 0));
        MostrarTodasCH.setText("Buscar");
        MostrarTodasCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarTodasCHActionPerformed(evt);
            }
        });

        jLabel3.setText("Folio Calcomanía:");

        jLabel1.setText("Tipo Calcomanía:");

        tipoCalcomania.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PROFECO", "UVA" }));

        jLabel2.setText("Estatus:");

        estatusHolograma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ASIGNADA", "NO ASIGNADA", "DAÑADO" }));

        RefrescarCH.setText("Refrescar");
        RefrescarCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefrescarCHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(folioHolograma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoCalcomania, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estatusHolograma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MostrarTodasCH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RefrescarCH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(folioHolograma, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MostrarTodasCH))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tipoCalcomania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(estatusHolograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(RefrescarCH)
                        .addContainerGap())))
        );

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea1.setRows(5);
        jTextArea1.setText("Para filtrar los campos primero\ndeben añadir información a los \ncampos y después darle clic a \nbuscar. Nota: Puede seleccionar\ndirectamente en la tabla para\nllenar el folio en automatico.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea1);

        AgregarCH1.setText("Agregar");
        AgregarCH1.setFocusable(false);
        AgregarCH1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AgregarCH1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AgregarCH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCH1ActionPerformed(evt);
            }
        });

        GenerarCH.setText("Generador Calcomanía");
        GenerarCH.setFocusable(false);
        GenerarCH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GenerarCH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        GenerarCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarCHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ModificarEstatusCH, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(eliminarFolio, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(GenerarCH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgregarCH1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(AgregarCH1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ModificarEstatusCH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminarFolio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GenerarCH)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarTodasCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarTodasCHActionPerformed
        // TODO add your handling code here:
        String folioH = folioHolograma.getText();
        String tipoH = (String)tipoCalcomania.getSelectedItem();
        String estatusH = (String) estatusHolograma.getSelectedItem();
        lbd.openConnection();
        modeloHologramas = lbd.modeloGasValid(columna, tipoH, folioH, estatusH);
        lbd.closeConnection();
        jTable1.setModel(modeloHologramas);
        modeloHologramas.fireTableDataChanged();
    }//GEN-LAST:event_MostrarTodasCHActionPerformed

    private void GenerarCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarCHActionPerformed
        GeneradorDeCalcomonia dialog = new GeneradorDeCalcomonia(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        //Victor Chan 16/02/2021
        //Metodo que detecta que la ventana se ha cerrado y procede a actualizar la tabla
        dialog.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                System.out.println("Estoy cerrando Generador de Calcomania");
                //Hacer lo que yo quiero          
                lbd.openConnection();
                modeloHologramas = lbd.modeloGasValid(columna, "", "", "");
                lbd.closeConnection();
                jTable1.setModel(modeloHologramas);
                modeloHologramas.fireTableDataChanged();
            }
        });
    }//GEN-LAST:event_GenerarCHActionPerformed

    private void RefrescarCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefrescarCHActionPerformed
        // TODO add your handling code here:
        lbd.openConnection();
        modeloHologramas = lbd.modeloGasValid(columna, "", "", "");
        lbd.closeConnection();
        jTable1.setModel(modeloHologramas);
        modeloHologramas.fireTableDataChanged();
    }//GEN-LAST:event_RefrescarCHActionPerformed

    private void ModificarEstatusCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarEstatusCHActionPerformed
      modificarHolograma dialog = new modificarHolograma(new javax.swing.JFrame(), true);
      dialog.setVisible(true);        // TODO add your handling code here:
      lbd.openConnection();
      modeloHologramas = lbd.modeloGasValid(columna, "", "", "");
      lbd.closeConnection();
      jTable1.setModel(modeloHologramas);
      modeloHologramas.fireTableDataChanged();
    }//GEN-LAST:event_ModificarEstatusCHActionPerformed

    private void eliminarFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarFolioActionPerformed
      EliminarFolios dialog = new EliminarFolios(new javax.swing.JFrame(), true);
      dialog.setVisible(true);
      // TODO add your handling code here:  // TODO add your handling code here:
      lbd.openConnection();
      modeloHologramas = lbd.modeloGasValid(columna, "", "", "");
      lbd.closeConnection();
      jTable1.setModel(modeloHologramas);
      modeloHologramas.fireTableDataChanged();
    }//GEN-LAST:event_eliminarFolioActionPerformed

    private void AgregarCH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCH1ActionPerformed
        //Victor Chan 24/02/2021
        agregarHologramas dialog = new agregarHologramas(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        lbd.openConnection();
        modeloHologramas = lbd.modeloGasValid(columna, "", "", "");
        lbd.closeConnection();
        jTable1.setModel(modeloHologramas);
        modeloHologramas.fireTableDataChanged();
        //Victor Chan 24/02/2021
        //Metodo que detecta que la ventana se ha cerrado y procede a actualizar la tabla
        dialog.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                System.out.println("Estoy cerrando Generador de AgregarHologramas");
                //Hacer lo que yo quiero          
                lbd.openConnection();
                modeloHologramas = lbd.modeloGasValid(columna, "", "", "");
                lbd.closeConnection();
                jTable1.setModel(modeloHologramas);
                modeloHologramas.fireTableDataChanged();
            }
        });
    }//GEN-LAST:event_AgregarCH1ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(catalogoHologramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(catalogoHologramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(catalogoHologramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(catalogoHologramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new catalogoHologramas().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCH1;
    private javax.swing.JButton GenerarCH;
    private javax.swing.JButton ModificarEstatusCH;
    private javax.swing.JButton MostrarTodasCH;
    private javax.swing.JButton RefrescarCH;
    private javax.swing.JButton eliminarFolio;
    private javax.swing.JComboBox estatusHolograma;
    private javax.swing.JTextField folioHolograma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox tipoCalcomania;
    // End of variables declaration//GEN-END:variables
}
